import numpy as np

REALMIN = np.finfo(float).tiny
REALMAX = np.finfo(float).max
RHOBEG_DEFAULT = 1
RHOEND_DEFAULT = 1e-6
FUNCMAX = 2.0**100
CONSTRMAX = FUNCMAX
EPS = np.finfo(float).eps
CTOL_DEFAULT = np.sqrt(EPS)
CWEIGHT_DEFAULT = 1e8
FTARGET_DEFAULT = -REALMAX
IPRINT_DEFAULT = False
MAXFUN_DIM_DEFAULT = 500
INFO_DEFAULT = 0
SMALL_TR_RADIUS = 0  # Why is this same as default?
MAXTR_REACHED = 20
DAMAGING_ROUNDING = 7
NAN_INF_X = -1
NAN_INF_F = -2
FTARGET_ACHIEVED = 1
MAXFUN_REACHED = 3